# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "uas" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];


################################################################################################
##
##
## check devices uuids after formatting/reinstalling, these uuids change.
##
##

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/57be5e6a-8269-48fb-82b2-452e78712e67";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FFFD-0657";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0e110245-2d45-41c8-ad16-8d38b8569bcb"; }
    ];

# /dev/disk/by-uuid/91f79ba4-4fab-4f79-91cd-0f7d16b136ce /run/media/pep/rust1tb ext4 rw,nosuid,nodev,relatime,errors=remount-ro 0 0
  fileSystems."/run/media/pep/rust1tb" =
    { device = "/dev/disk/by-uuid/91f79ba4-4fab-4f79-91cd-0f7d16b136ce";
      fsType = "ext4";
      options = [
        "users"
        "nofail"
      ];
    };

##
##
##
################################################################################################

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
