# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "uas" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

################################################################################################
##
##
## check devices uuids after formatting/reinstalling, these uuids change.
## (regenerated 2026-09-23 after the reinstall)
##

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/04f335fe-b8a0-4711-a799-94d81bf3e7cc";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/564D-6EB6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/dedeba77-70eb-4d86-8be9-fdce8471532e"; }
    ];

# the 1TB spinning rust data disk (/dev/sdb), uuid survived the reinstall
  fileSystems."/run/media/pep/rust1tb" =
    { device = "/dev/disk/by-uuid/91f79ba4-4fab-4f79-91cd-0f7d16b136ce";
      fsType = "ext4";
      options = [
        "users"
        "nofail"
      ];
    };

##
##
##
################################################################################################

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
